version: "3"
services:
  users_backend:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - .dbdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
